In [1]:
# Load dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB

In [11]:
# Load Train and Test datasets
data_train = pd.read_csv('Resources/data_train.csv', index_col=0)
data_test = pd.read_csv('Resources/data_test.csv', index_col=0)

In [12]:
# Using features from Random Forest model to reduce total number for NB model
important_features = ['step02h_eqparamA', 'step02t_eqparamA', 'step03t_eqparamA',
       'step10h_eqparamA', 'step12h_eqparamA', 'step01bt_eqparamB',
       'step04t_eqparamB', 'step05t_eqparamB', 'system_state']

In [14]:
# Set target and data for train and test
train_target = data_train.system_result
train_data = data_train.loc[:,important_features]
test_target = data_test.system_result
test_data = data_test.loc[:,important_features]
train_data.head()

step02h_eqparamA  step02t_eqparamA  step03t_eqparamA  step10h_eqparamA  \
204         10.206160          5.269793         14.571557         10.359803   
288         11.594693         12.964035         18.818674         10.000000   
10          13.908432          9.577346         17.182340         11.961294   
343         12.587146          9.169558         18.431346         10.873549   
12          15.121956         11.482360         18.202655          8.266934   

     step12h_eqparamA  step01bt_eqparamB  step04t_eqparamB  step05t_eqparamB  \
204          9.275444           1.097459          0.727515          0.793088   
288         11.994222           1.422882          0.702225          0.659266   
10           8.390811           0.817278          0.668262          0.613816   
343         13.109344           1.476915          0.763383          0.759087   
12           4.686747           0.532814          0.598675          0.570682   

     system_state  
204     72.356881  
288    129.070620  
10     161.511362  
343    120.920581  
12     103.095827

In [15]:
# Run the model using all features
nb = GaussianNB()
nb = nb.fit(train_data, train_target)
nb.score(test_data, test_target)

0.6774193548387096

In [16]:
# classification report and confusion matrix
from sklearn.metrics import classification_report, confusion_matrix
target_pred = nb.predict(test_data)
print(confusion_matrix(test_target, target_pred))
print(classification_report(test_target, target_pred))

[[18  7  1]
 [ 9 24  0]
 [ 0  3  0]]
              precision    recall  f1-score   support

         Bad       0.67      0.69      0.68        26
        Good       0.71      0.73      0.72        33
     Warning       0.00      0.00      0.00         3

    accuracy                           0.68        62
   macro avg       0.46      0.47      0.47        62
weighted avg       0.66      0.68      0.67        62



In [17]:
# save fitted model to file
import joblib
filename = 'naive_bayes.sav'
joblib.dump(nb, filename)

['naive_bayes.sav']